config/routes.rb
Pastr::Application.routes.draw do
  root :to => "home#index"

  resources :pasties, :except=>[:index]

  get 'pastie/show/:slug' => "pasties#by_slug", :as=>:show_by_slug

end

app/models/pastie.rb
class Pastie < ActiveRecord::Base
  before_validation 'get_id(8)'




  private

  def get_id length
    return unless self.slug.nil?
    character_set = [(0..9).collect(&:to_s).to_a, ('a'..'z').to_a, ('A'..'Z').to_a].flatten
    tmp_id = (1..length).collect{ character_set[rand(character_set.length)] }.join
    while Pastie.exists?(:slug=>tmp_id) do
      tmp_id.next!
    end
    self.slug = tmp_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @pastie = Pastie.last
    @pasties = Pastie.all( :order=>"created_at desc", :limit=>5 )
  end
end

app/controllers/pasties_controller.rb
class PastiesController < ApplicationController

  def create
    pastie = Pastie.new :content=>params[:pastie][:content].to_s.strip, :title=>params[:pastie][:title]
    pastie.save!
    redirect_to show_by_slug_path( :slug=>pastie.slug )
  end

  def new

  end

  def show

  end

  def by_slug
    #We are going to assume it's always going to be
    @pastie = Rails.cache.fetch( params[:slug] ) do
        Pastie.find_by_slug(params[:slug])
      end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_facebook_like.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like" data-href="pasties.herokuapp.com" data-send="false" data-layout="box_count" data-width="450" data-show-faces="true" data-action="recommend" data-font="tahoma"></div>

app/views/home/_tweet_button.html.erb
<a href="https://twitter.com/share" class="twitter-share-button" data-count="vertical">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>

app/views/home/index.html.erb
<h2>Paste your stuff here</h2>

<div id='content' style="width: 65%; float: left; padding-left: 10px; padding-right: 10px;">
<%= render :partial=>"pastie/show" %>
</div>
<div id='pasties' style="float: left; width: 29%">
 <%=link_to "Create a pasty", new_pasty_url %>

 <div id="paste_boxes" style="width: 100%">
    <%= render :partial=>"pastie/box", :collection=>@pasties %>
 </div>
 <div id="social_buttons" style="padding-top: 10px;">
    <%= render :partial=>"facebook_like" %>
    <%= render :partial=>"tweet_button" %>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pasties::Easy to use online clipboard and copier</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pastie/_box.html.erb
<div class="front_pasties">
  <span style="color: red;"><%= box.title.nil? ? "None" : box.title %></span><br />
  <span style="color: red"><%=box.author.nil? ? "Anonymous" : box.author %> </span><br />
  <div style="text-align: center">ID: <%= link_to box.slug, show_by_slug_url(:slug=>box.slug) %></div> <br />
</div>

app/views/pastie/_show.html.erb
<script src="http://yandex.st/highlightjs/6.1/highlight.min.js"></script>
<link rel="stylesheet" href="http://yandex.st/highlightjs/6.1/styles/default.min.css">

 <script>
  hljs.tabReplace = '    ';
  hljs.initHighlightingOnLoad();
 </script>

<% if @pastie.nil? %>
    Nothing to see here
<% else %>
    Created on: <%=@pastie.created_at.strftime("%m/%d/%Y %H:%M") %> <br/>
    <div class="pastie_content">
      <pre>
        <code><%= @pastie.content %>
        </code>
      </pre>
    </div>
    <div id="pastie_raw" class="pastie_content">
      <%= form_for @pastie do |f| %>
        Raw Text
        <pre>
            <%= f.text_area :content, :size=>"72x20" %>
        </pre>
        <p>
          <div id="pastie_url">
            URL: <%= text_field_tag :url, show_by_slug_url( @pastie.slug ), :size=>40 %>
          </div>
        </p>
      <% end %>
    </div>
<% end %>

app/views/pasties/by_slug.html.erb
<h2>Pastie <%= @pastie.slug%></h2>
<%= render :partial=>"/pastie/show" %>


<%= link_to "Back to home", root_url %>

app/views/pasties/create.html.erb
That's right I created this!

app/views/pasties/new.html.erb
<%= form_for Pastie.new do |f| %>
    Pastie: <br /><br />
    <%= f.text_area :content, :size=>"60x12" %>
    <br />
    Title: <%= f.text_field :title %><br />
    <br/><br/>
    <%= f.submit( "Paste" ) %>
    <br />
<% end %>

<%= link_to "I changed my mind. Take me back to the homepage.", root_url %>

app/views/pasties/show.html.erb
<%= render :partial=>'pastie/show' %>